---
- name: Running Ubuntu Automation with Ansible
  gather_facts: no
  connection: local
  hosts: all
  become: yes

  tasks:
  - name: Push Command Shell
    shell: |
      ping 8.8.8.8 -c 3
      ping 192.168.1.101 -c 3
      ping 1.1.1.1 -c 3
      ping 192.168.1.102 -c 3
      ping 9.9.9.9 -c 3
      ping 192.168.1.103 -c 3
    register: result

  - name: print output
    debug:
      var: result.stdout_lines